// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "bibbgaares-20190208110136-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://bibbgaares-20190208110136-hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:1aa512a4-fdb0-4762-ab3c-cfa1956c9f96",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_OiSViHr1a",
    "aws_user_pools_web_client_id": "2gho8vq30qviksumrm6b4f1mh3",
    "aws_mobile_analytics_app_id": "e366ae756e604753b04c6539c030e1c3",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_user_files_s3_bucket": "bibbgaares52fbb470918947319a396ebb58526e2c",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://cps2wy3yb5a3tddeg7my3q7nny.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
